let a = 'test';
let b = 'check drafting';
let news = 'new fix';
let newbie = 'new hotfix branch test';
let newCheck = 'new checking';
let love = 'love new changes';
let checknew = 'new';
let check = 'new check'
let lastest = 'lastest check';
