name: Create New Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Hotfix branch name
        required: true

jobs:
  create-branch:
    name: Create New Branch
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'hotfix/${{ github.event.inputs.branch_name }}'
