name: Create New Hotfix Branch

on:
  workflow_dispatch:

jobs:
  create-branch:
    name: Create New Branch
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    steps:
      - name: Create hotfix Branch
        id: create-release
        env:
          HUSKY: 0
        run: |
          source_branch_name=${GITHUB_REF##*/}
          git fetch origin main --depth=1
          git merge origin/main
          current_version=$(jq -r .version package.json)

          npm version patch --no-git-tag-version
          new_version=$(jq -r .version package.json)
          git reset --hard

          branch_name="hotfix/${new_version}"

          echo "New hotfix branch name is $branch_name"
          git checkout -b "$branch_name"
          git push --set-upstream origin "$branch_name"
          echo "::set-output name=source_branch_name::$source_branch_name"
          echo "::set-output name=branch_name::$branch_name"
