name: Deploy Configurations To Sources Development DB

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        env:
          HUSKY: 0
        run: |
          npm ci
      - name: Execute Unit Tests
        env:
          HUSKY: 0
        run: |
          npm run test


      - name: Deploy To Sources Development DB
        run: |
          python scripts/deployToDB.py https://sources-api.dev.rudderlabs.com
