name: Deploy Configurations To Production DB

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        env:
          HUSKY: 0
        run: |
          npm ci
      - name: Execute Unit Tests
        env:
          HUSKY: 0
        run: |
          npm run test
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Deploy To Production DB
        run: |
           echo "🍏 prod deployment complete."
